source/accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from accounts.views import RegisterView, RegisterActivateView, UserDetailView, \
    UserChangeView, UserPasswordChangeView, UserPasswordResetEmailView, UserPasswordResetView

app_name = 'accounts'

urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='create'),
    path('activate/<uuid:token>/', RegisterActivateView.as_view(), name='activate'),
    path('<int:pk>/', UserDetailView.as_view(), name='detail'),
    path('<int:pk>/update/', UserChangeView.as_view(), name='change'),
    path('password-change/', UserPasswordChangeView.as_view(), name='password_change'),
    path('password-reset/', UserPasswordResetEmailView.as_view(), name='password_reset_email'),
    path('password-reset/<uuid:token>/', UserPasswordResetView.as_view(), name='password_reset')
]

source/hello/urls.py
from django.conf.urls import url
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns


urlpatterns = [
    path('api/v1/', include('api_v1.urls')),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
]

urlpatterns += i18n_patterns(
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('webapp.urls')),
    prefix_default_language=False
)

urlpatterns += [path('silk/', include('silk.urls', namespace='silk'))]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

source/webapp/urls.py
from django.urls import path, include
from webapp.views import IndexView, ArticleCreateView, ArticleView, \
    ArticleUpdateView, ArticleDeleteView, \
    ArticleCommentCreateView, ArticleMassActionView, \
    CommentUpdateView, CommentDeleteView, ArticleLikeView, ArticleUnLikeView

app_name = 'webapp'

urlpatterns = [
    path('', IndexView.as_view(), name='index'),

    path('article/', include([
        path('<int:pk>/', include([
            path('', ArticleView.as_view(), name='article_view'),
            path('update/', ArticleUpdateView.as_view(), name='article_update'),
            path('delete/', ArticleDeleteView.as_view(), name='article_delete'),
            path('comments/add/', ArticleCommentCreateView.as_view(),
                 name='article_comment_add'),
            path('like/', ArticleLikeView.as_view(), name='article_like'),
            path('unlike/', ArticleUnLikeView.as_view(), name='article_unlike'),
        ])),

        path('add/', ArticleCreateView.as_view(), name='article_create'),
        path('mass-action/', ArticleMassActionView.as_view(), name='article_mass_action'),
    ])),

    path('comment/', include([
        path('<int:pk>/', include([
            path('update/', CommentUpdateView.as_view(), name='comment_update'),
            path('delete/', CommentDeleteView.as_view(), name='comment_delete'),
        ]))
    ]))
]

source/webapp/models.py
from django.contrib.auth import get_user_model
from django.core.validators import MinLengthValidator
from django.db import models
from django.utils import timezone

STATUS_NEW = 'new'
STATUS_MODERATED = 'moderated'
STATUS_REJECTED = 'rejected'
STATUS_CHOICES = [
    (STATUS_NEW, 'Не модерировано'),
    (STATUS_MODERATED, 'Модерировано'),
    (STATUS_REJECTED, 'Отклонено')
]
ACCESS_OPEN = 'shared'
ACCESS_HIDDEN = 'hidden'
ACCESS_CLOSED = 'private'
ACCESS_CHOICES = [
    (ACCESS_OPEN, 'Общий'),
    (ACCESS_HIDDEN, 'Скрытый'),
    (ACCESS_CLOSED, 'Приватный'),
]

class Article(models.Model):
    title = models.CharField(max_length=200, null=False, blank=False, verbose_name='Заголовок',
                             validators=[MinLengthValidator(10)])
    text = models.TextField(max_length=3000, null=False, blank=False, verbose_name='Текст')
    author = models.ForeignKey(get_user_model(), on_delete=models.SET_DEFAULT, default=1,
                               related_name='articles', verbose_name='Автор')
    status = models.CharField(max_length=15, choices=STATUS_CHOICES, default=STATUS_NEW, verbose_name='Модерация')
    tags = models.ManyToManyField('webapp.Tag', related_name='articles', blank=True, verbose_name='Теги')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Время создания')
    updated_at = models.DateTimeField(auto_now=True, verbose_name='Время изменения')
    publish_at = models.DateTimeField(verbose_name="Время публикации", blank=True, default=timezone.now)
    like_count = models.IntegerField(verbose_name="Счётчик лайков", default=0)
    access = models.CharField(max_length=15, choices=ACCESS_CHOICES, default=ACCESS_OPEN, verbose_name='Доступ')
    access_list = models.ManyToManyField(get_user_model(), related_name='access_articles', 
                                         verbose_name='Кому доступен файл', blank=True)

    def save(self, **kwargs):
        if not self.publish_at:
            if not self.pk:
                self.publish_at = timezone.now()
            else:
                self.publish_at = Article.objects.get(pk=self.pk).publish_at
        super().save(**kwargs)

    # @property
    # def comment_count(self):
    #     return self.comments.count()

    def liked_by(self, user):
        likes = self.likes.filter(user=user)
        return likes.count() > 0

    def __str__(self):
        return "{}. {}".format(self.pk, self.title)

    class Meta:
        verbose_name = 'Статья'
        verbose_name_plural = 'Статьи'


class Comment(models.Model):
    article = models.ForeignKey('webapp.Article', related_name='comments',
                                on_delete=models.CASCADE, verbose_name='Статья')
    text = models.TextField(max_length=400, verbose_name='Комментарий')
    author = models.ForeignKey(get_user_model(), on_delete=models.SET_DEFAULT, default=1,
                               related_name='comments', verbose_name='Автор')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Время создания')
    updated_at = models.DateTimeField(auto_now=True, verbose_name='Время изменения')

    def __str__(self):
        return self.text[:20]

    class Meta:
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'


class Tag(models.Model):
    name = models.CharField(max_length=31, verbose_name='Тег')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Время создания')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Тег'
        verbose_name_plural = 'Теги'


class ArticleLike(models.Model):
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, 
                             related_name='article_likes', verbose_name='Пользователь')
    article = models.ForeignKey('webapp.Article', on_delete=models.CASCADE,
                                related_name='likes', verbose_name='Статья')

    def __str__(self):
        return f'{self.user.username} - {self.article.title}'

    class Meta:
        verbose_name = 'Лайк'
        verbose_name_plural = 'Лайки статей'

source/webapp/views/article_views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin, \
    UserPassesTestMixin
from django.core.paginator import Paginator
from django.db.models import Count
from django.http import HttpResponse, HttpResponseForbidden
from django.shortcuts import redirect, get_object_or_404
from django.urls import reverse, reverse_lazy
from django.utils.timezone import make_naive
from django.views.generic import View, DetailView, CreateView, UpdateView, DeleteView

from webapp.models import Article, Tag, ArticleLike, STATUS_MODERATED, ACCESS_OPEN, ACCESS_CLOSED
from webapp.forms import ArticleForm, BROWSER_DATETIME_FORMAT
from .base_views import SearchView
from django.core.cache import cache


class IndexView(SearchView):
    template_name = 'article/index.html'
    context_object_name = 'articles'
    paginate_by = 5
    paginate_orphans = 0
    model = Article
    ordering = ['-created_at']
    search_fields = ['title__icontains', 'author__icontains']
    extra_context = {'version': 'v1'}

    def get_queryset(self):
        key = f'article_list_{self.request.GET.get("page", 1)}'
        data = cache.get(key)
        if data is None:
            data = super().get_queryset()
            if not self.request.GET.get('is_admin', None):
                data = data.filter(status=STATUS_MODERATED, access=ACCESS_OPEN)\
                    .select_related('author')\
                    .prefetch_related('tags')\
                    .annotate(comment_count=Count('comments'))
            cache.set(key, data, 60)
        return data


class ArticleMassActionView(PermissionRequiredMixin, View):
    redirect_url = 'webapp:index'
    permission_required = 'webapp.delete_article'
    queryset = None  # изначально queryset = None

    def has_permission(self):
        if super().has_permission():
            return True  # админы и модеры могут удалять
        articles = self.get_queryset()
        author_ids = articles.values('author_id')
        for item in author_ids:
            if item['author_id'] != self.request.user.pk:
                return False  # остальные могут удалять, только если среди выбранных статей
        return True           # нет чужих статей

    # метод 'post' проверяет наличие ключа 'delete' в запросе,
    # и тогда удаляет
    def post(self, request, *args, **kwargs):
        if 'delete' in self.request.POST:
            return self.delete(request, *args, **kwargs)
        return redirect(self.redirect_url)

    # метод 'delete' не проверяет наличие ключа 'delete' в запросе,
    # и все равно удаляет
    def delete(self, request, *args, **kwargs):
        queryset = self.get_queryset()
        queryset.delete()
        return redirect(self.redirect_url)

    # "кэширующий" метод.
    # при первом доступе к свойству queryset находит и сохраняет его в self.queryset
    # при повторном доступе не ищет, возвращает сохранённое значение.
    def get_queryset(self):
        if self.queryset is None:
            ids = self.request.POST.getlist('selected_articles', [])
            self.queryset = self.get_queryset().filter(id__in=ids)
        return self.queryset


class ArticleView(UserPassesTestMixin, DetailView):
    template_name = 'article/article_view.html'
    model = Article
    paginate_comments_by = 2
    paginate_comments_orphans = 0

    def test_func(self):
        article = self.get_object()
        return article.access != ACCESS_CLOSED \
               or self.request.user == article.author \
               or self.request.user in article.access_list.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        comments, page, is_paginated = self.paginate_comments(self.object)
        context['comments'] = comments
        context['page_obj'] = page
        context['is_paginated'] = is_paginated

        return context

    def paginate_comments(self, article):
        comments = article.comments.all().order_by('-created_at')
        if comments.count() > 0:
            paginator = Paginator(comments, self.paginate_comments_by, orphans=self.paginate_comments_orphans)
            page_number = self.request.GET.get('page', 1)
            page = paginator.get_page(page_number)
            is_paginated = paginator.num_pages > 1  # page.has_other_pages()
            return page.object_list, page, is_paginated
        else:
            return comments, None, False


class ArticleCreateView(LoginRequiredMixin, CreateView):
    template_name = 'article/article_create.html'
    form_class = ArticleForm
    model = Article

    # def form_valid(self, form):
    #     form.instance.author = self.request.user
    #     response = super().form_valid(form)
    #     tag, _ = Tag.objects.get_or_create(name=self.request.user.username)
    #     form.instance.tags.add(tag)
    #     return response
    #
    # def get_success_url(self):
    #     return reverse('webapp:article_view', kwargs={'pk': self.object.pk})

    def form_valid(self, form):
        article = form.save(commit=False)
        article.author = self.request.user
        article.save()
        form.save_m2m()
        tag, _ = Tag.objects.get_or_create(name=self.request.user.username)
        article.tags.add(tag)
        return redirect('webapp:article_view', pk=article.pk)


class ArticleUpdateView(PermissionRequiredMixin, UpdateView):
    template_name = 'article/article_update.html'
    form_class = ArticleForm
    model = Article
    permission_required = 'webapp.change_article'

    def has_permission(self):
        article = self.get_object()
        return super().has_permission() or article.author == self.request.user

    def get_initial(self):
        return {'publish_at': make_naive(self.object.publish_at)\
            .strftime(BROWSER_DATETIME_FORMAT)}

    # def form_valid(self, form):
    #     response = super().form_valid(form)
    #     tag, _ = Tag.objects.get_or_create(name=self.request.user.username)
    #     form.instance.tags.add(tag)
    #     return response
    #
    # def get_success_url(self):
    #     return reverse('webapp:article_view', kwargs={'pk': self.object.pk})

    def form_valid(self, form):
        article = form.save()
        tag, _ = Tag.objects.get_or_create(name=self.request.user.username)
        article.tags.add(tag)
        return redirect('webapp:article_view', pk=article.pk)


class ArticleDeleteView(UserPassesTestMixin, DeleteView):
    template_name = 'article/article_delete.html'
    model = Article
    success_url = reverse_lazy('webapp:index')

    def test_func(self):
        return self.request.user.has_perm('webapp.delete_article') or \
            self.get_object().author == self.request.user


class ArticleLikeView(LoginRequiredMixin, View):
    def post(self, request, *args, **kwargs):
        article = get_object_or_404(Article, pk=kwargs.get('pk'))
        like, created = ArticleLike.objects.get_or_create(article=article, user=request.user)
        if created:
            article.like_count += 1
            article.save()
            return HttpResponse(article.like_count)
        else:
            return HttpResponseForbidden()


class ArticleUnLikeView(LoginRequiredMixin, View):
    def delete(self, request, *args, **kwargs):
        article = get_object_or_404(Article, pk=kwargs.get('pk'))
        like = get_object_or_404(article.likes, user=request.user)
        like.delete()
        article.like_count -= 1
        article.save()
        return HttpResponse(article.like_count)


class GrantAccessView(LoginRequiredMixin, View):
    def post(self, request, *args, **kwargs):
        article = get_object_or_404(Article, pk=kwargs.get('pk'))
        user = get_object_or_404(get_user_model(), username=request.POST.get('username'))
        article.access_list.add(user)
        return HttpResponse('{"status": "ok"}')


class RemoveAccessView(LoginRequiredMixin, View):
    def post(self, request, *args, **kwargs):
        article = get_object_or_404(Article, pk=kwargs.get('pk'))
        user = get_object_or_404(get_user_model(), username=request.POST.get('username'))
        article.access_list.remove(user)
        return HttpResponse('{"status": "ok"}')

source/webapp/views/comment_views.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse
from django.views.generic import CreateView, UpdateView, DeleteView

from webapp.models import Comment, Article
from webapp.forms import ArticleCommentForm


class ArticleCommentCreateView(LoginRequiredMixin, CreateView):
    model = Comment
    template_name = 'comment/comment_create.html'
    form_class = ArticleCommentForm

    def form_valid(self, form):
        article = get_object_or_404(Article, pk=self.kwargs.get('pk'))
        comment = form.save(commit=False)
        comment.article = article
        comment.author = self.request.user
        comment.save()
        # form.save_m2m()  ## для сохранения связей многие-ко-многим
        return redirect('webapp:article_view', pk=article.pk)


class CommentUpdateView(PermissionRequiredMixin, UpdateView):
    model = Comment
    template_name = 'comment/comment_update.html'
    form_class = ArticleCommentForm
    permission_required = 'webapp.change_comment'

    def has_permission(self):
        comment = self.get_object()
        return super().has_permission() or comment.author == self.request.user

    def get_success_url(self):
        return reverse('webapp:article_view', kwargs={'pk': self.object.article.pk})


class CommentDeleteView(PermissionRequiredMixin, DeleteView):
    model = Comment
    permission_required = 'webapp.delete_comment'

    def get(self, request, *args, **kwargs):
        return self.delete(request, *args, **kwargs)

    def has_permission(self):
        comment = self.get_object()
        return super().has_permission() or comment.author == self.request.user

    def get_success_url(self):
        return reverse('webapp:article_view', kwargs={'pk': self.object.article.pk})

source/webapp/templates/partial/article_list.html
{% load likes %}
{% load cache %}

{% if is_paginated %}
    {% include 'partial/pagination.html' %}
{% endif %}

{% if show_mass_delete %}
    <form action="{% url "webapp:article_mass_action" %}" method="post">
        {% csrf_token %}
        <p class="mass-actions"><input type="submit" name="delete" value="Delete selected"></p>
{% endif %}
        {% cache 30 article_list user.is_authenticated user.username page_obj.number %}
            {% for article in articles %}
                <div class="box">
                    <h3><a href="{% url "webapp:article_view" article.pk %}">{{ article.title }} ({{ article.comment_count }})</a></h3>
                    {% if show_mass_delete %}
                        <p>
                            <label for="selected_articles-{{ article.pk }}">Select:</label>
                            <input type="checkbox" name="selected_articles"
                                   id="selected_articles-{{ article.pk }}" value="{{ article.pk }}">
                        </p>
                    {% endif %}
                    <p>Статус: ({{ article.status }} | {{ article.get_status_display }})</p>
                    <p>
                        <a href="{% url 'accounts:detail' article.author_id %}">{{ article.author }}</a>
                        | {{ article.created_at|date:"d.m.Y H:i:s" }}
                    </p>
                    <p>Published at: {{ article.publish_at|date:"d.m.Y H:i:s" }}</p>
                    <p>Tags: {% for tag in article.tags.all %}{{ tag.name }}{% if not forloop.last %}, {% endif %}{% endfor %}</p>
                    {% if perms.webapp.change_article or article.author == request.user %}
                        <p><a href="{% url 'webapp:article_update' article.pk %}">Update</a></p>
                    {% endif %}
                    {% if perms.webapp.delete_article or article.author == request.user %}
                        <p><a href="{% url 'webapp:article_delete' article.pk %}">Delete</a></p>
                    {% endif %}
                    {% if user.is_authenticated %}
                        <p>
                            <span class="counter">{{ article.like_count }}</span>
                            {% with article|liked_by:user as liked %}
                                <a class="{% if liked %}hidden{% endif %} like" href="{% url 'webapp:article_like' article.pk %}">Like</a>
                                <a class="{% if not liked %}hidden{% endif %} unlike" href="{% url 'webapp:article_unlike' article.pk %}">Unlike</a>
                            {% endwith %}
                        </p>
                    {% endif %}
                </div>
            {% empty %}
                <h2 class="text-center">Нет статей</h2>
            {% endfor %}
        {% endcache %}
{% if show_mass_delete %}
    </form>
{% endif %}

{% if is_paginated %}
    {% include 'partial/pagination.html' %}
{% endif %}

source/webapp/templates/partial/form.html
{% if not fields_only %}
    <form action="{{ action_url }}" method="{{ form_method }}" enctype="{{ enctype }}" id="{{ form_id }}">
        {% csrf_token %}
{% endif %}

        {% for error in form.non_field_errors %}
            <p class="error">{{ error }}</p>
        {% endfor %}

        {% for field in form %}
            {% include 'partial/form_field.html' %}
        {% endfor %}

{% if not fields_only %}
        <br/>
        <input type="submit" id="submit" value="{{ button_text|default:"Submit" }}"/>
    </form>
{% endif %}

source/webapp/templates/partial/form_field.html
{% load widget_tweaks %}

<label for="{{ field.id_for_label }}">
    {% if field.field.required %}
        <span class="red">*</span>
    {% endif %}
    {{ field.label }}:
</label>
<br/>
{% if field|field_type == 'modelmultiplechoicefield' %}
    {{ field|add_class:'form-checkboxes'|add_error_class:'form-error' }}
{% else %}
    {{ field|add_class:'form-input'|add_error_class:'form-error' }}
{% endif %}
<br/>
{% for error in field.errors %}
    <p class="error">{{ error }}</p>
{% endfor %}
<br/>

source/webapp/templates/partial/pagination.html
{% load page_utils %}

<div class="pagination">
    <span class="step-links">
        <a href="?{{ request|page_query_string:1 }}">&laquo; В начало</a>

        {% if page_obj.has_previous %}
            <a href="?{{ request|page_query_string:page_obj.previous_page_number }}">Назад</a>
        {% else %}
            <span class="page-disabled">Назад</span>
        {% endif %}


        <form class="current-page" method="get">
            <label for="page">
                {% for key, value in request.GET.items %}
                    {% if not key == 'page' %}
                        <input type="hidden" name="{{ key }}" value="{{ value }}">
                    {% endif %}
                {% endfor %}
                Страница <input type="text" name="page" id="page" value="{{ page_obj.number }}">
                из {{ page_obj.paginator.num_pages }}.
            </label>
        </form>

        {% if page_obj.has_next %}
            <a href="?{{ request|page_query_string:page_obj.next_page_number }}">Далее</a>
        {% else %}
            <span class="page-disabled">Далее</span>
        {% endif %}

        <a href="?{{ request|page_query_string:page_obj.paginator.num_pages }}">В конец &raquo;</a>
    </span>
</div>