source/accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from accounts.views import RegisterView, RegisterActivateView, UserDetailView, \
    UserChangeView, UserPasswordChangeView, UserPasswordResetEmailView, UserPasswordResetView

app_name = 'accounts'

urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='create'),
    path('activate/<uuid:token>/', RegisterActivateView.as_view(), name='activate'),
    path('<int:pk>/', UserDetailView.as_view(), name='detail'),
    path('<int:pk>/update/', UserChangeView.as_view(), name='change'),
    path('password-change/', UserPasswordChangeView.as_view(), name='password_change'),
    path('password-reset/', UserPasswordResetEmailView.as_view(), name='password_reset_email'),
    path('password-reset/<uuid:token>/', UserPasswordResetView.as_view(), name='password_reset')
]

source/hello/urls.py
from django.conf.urls import url
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns


urlpatterns = [
    path('api/v1/', include('api_v1.urls')),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
]

urlpatterns += i18n_patterns(
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('webapp.urls')),
    prefix_default_language=False
)

urlpatterns += [path('silk/', include('silk.urls', namespace='silk'))]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

source/webapp/urls.py
from django.urls import path, include
from webapp.views import IndexView, ArticleCreateView, ArticleView, \
    ArticleUpdateView, ArticleDeleteView, \
    ArticleCommentCreateView, ArticleMassActionView, \
    CommentUpdateView, CommentDeleteView, ArticleLikeView, ArticleUnLikeView

app_name = 'webapp'

urlpatterns = [
    path('', IndexView.as_view(), name='index'),

    path('article/', include([
        path('<int:pk>/', include([
            path('', ArticleView.as_view(), name='article_view'),
            path('update/', ArticleUpdateView.as_view(), name='article_update'),
            path('delete/', ArticleDeleteView.as_view(), name='article_delete'),
            path('comments/add/', ArticleCommentCreateView.as_view(),
                 name='article_comment_add'),
            path('like/', ArticleLikeView.as_view(), name='article_like'),
            path('unlike/', ArticleUnLikeView.as_view(), name='article_unlike'),
        ])),

        path('add/', ArticleCreateView.as_view(), name='article_create'),
        path('mass-action/', ArticleMassActionView.as_view(), name='article_mass_action'),
    ])),

    path('comment/', include([
        path('<int:pk>/', include([
            path('update/', CommentUpdateView.as_view(), name='comment_update'),
            path('delete/', CommentDeleteView.as_view(), name='comment_delete'),
        ]))
    ]))
]

source/webapp/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.core.validators import BaseValidator
from django.utils.deconstruct import deconstructible

from .models import STATUS_CHOICES, Article, Comment

default_status = STATUS_CHOICES[0][0]


BROWSER_DATETIME_FORMAT = '%d.%m.%Y %H:%M'


class XDatepickerWidget(forms.TextInput):
    template_name = 'widgets/xdatepicker_widget.html'


def at_least_10(string):
    if len(string) < 10:
        raise ValidationError('This value is too short!')


@deconstructible
class MinLengthValidator(BaseValidator):
    message = 'Value "%(value)s" has length of %(show_value)d! It should be at least %(limit_value)d symbols long!'
    code = 'too_short'

    def compare(self, value, limit):
        return value < limit

    def clean(self, value):
        return len(value)


class ArticleForm(forms.ModelForm):
    publish_at = forms.DateTimeField(required=False, label='Время публикации',
                                     input_formats=['%Y-%m-%d', BROWSER_DATETIME_FORMAT,
                                                    '%Y-%m-%dT%H:%M:%S', '%Y-%m-%d %H:%M',
                                                    '%Y-%m-%d %H:%M:%S'],
                                     widget=XDatepickerWidget)

    class Meta:
        model = Article
        fields = ['title', 'text', 'status', 'publish_at', 'tags']
        widgets = {'tags': forms.CheckboxSelectMultiple}

    def clean(self):
        cleaned_data = super().clean()
        errors = []
        text = cleaned_data.get('text')
        title = cleaned_data.get('title')
        if text and title and text == title:
            errors.append(ValidationError("Text of the article should not duplicate it's title!"))
        if errors:
            raise ValidationError(errors)
        return cleaned_data


# class CommentForm(forms.Form):
#     article = forms.ModelChoiceField(queryset=Article.objects.all(), required=True, label='Статья')


class SimpleSearchForm(forms.Form):
    search = forms.CharField(max_length=100, required=False, label="Найти")


class ArticleCommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['text']

source/webapp/views/article_views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin, \
    UserPassesTestMixin
from django.core.paginator import Paginator
from django.db.models import Count
from django.http import HttpResponse, HttpResponseForbidden
from django.shortcuts import redirect, get_object_or_404
from django.urls import reverse, reverse_lazy
from django.utils.timezone import make_naive
from django.views.generic import View, DetailView, CreateView, UpdateView, DeleteView

from webapp.models import Article, Tag, ArticleLike, STATUS_MODERATED, ACCESS_OPEN, ACCESS_CLOSED
from webapp.forms import ArticleForm, BROWSER_DATETIME_FORMAT
from .base_views import SearchView
from django.core.cache import cache


class IndexView(SearchView):
    template_name = 'article/index.html'
    context_object_name = 'articles'
    paginate_by = 5
    paginate_orphans = 0
    model = Article
    ordering = ['-created_at']
    search_fields = ['title__icontains', 'author__icontains']
    extra_context = {'version': 'v1'}

    def get_queryset(self):
        key = f'article_list_{self.request.GET.get("page", 1)}'
        data = cache.get(key)
        if data is None:
            data = super().get_queryset()
            if not self.request.GET.get('is_admin', None):
                data = data.filter(status=STATUS_MODERATED, access=ACCESS_OPEN)\
                    .select_related('author')\
                    .prefetch_related('tags')\
                    .annotate(comment_count=Count('comments'))
            cache.set(key, data, 60)
        return data


class ArticleMassActionView(PermissionRequiredMixin, View):
    redirect_url = 'webapp:index'
    permission_required = 'webapp.delete_article'
    queryset = None  # изначально queryset = None

    def has_permission(self):
        if super().has_permission():
            return True  # админы и модеры могут удалять
        articles = self.get_queryset()
        author_ids = articles.values('author_id')
        for item in author_ids:
            if item['author_id'] != self.request.user.pk:
                return False  # остальные могут удалять, только если среди выбранных статей
        return True           # нет чужих статей

    # метод 'post' проверяет наличие ключа 'delete' в запросе,
    # и тогда удаляет
    def post(self, request, *args, **kwargs):
        if 'delete' in self.request.POST:
            return self.delete(request, *args, **kwargs)
        return redirect(self.redirect_url)

    # метод 'delete' не проверяет наличие ключа 'delete' в запросе,
    # и все равно удаляет
    def delete(self, request, *args, **kwargs):
        queryset = self.get_queryset()
        queryset.delete()
        return redirect(self.redirect_url)

    # "кэширующий" метод.
    # при первом доступе к свойству queryset находит и сохраняет его в self.queryset
    # при повторном доступе не ищет, возвращает сохранённое значение.
    def get_queryset(self):
        if self.queryset is None:
            ids = self.request.POST.getlist('selected_articles', [])
            self.queryset = self.get_queryset().filter(id__in=ids)
        return self.queryset


class ArticleView(UserPassesTestMixin, DetailView):
    template_name = 'article/article_view.html'
    model = Article
    paginate_comments_by = 2
    paginate_comments_orphans = 0

    def test_func(self):
        article = self.get_object()
        return article.access != ACCESS_CLOSED \
               or self.request.user == article.author \
               or self.request.user in article.access_list.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        comments, page, is_paginated = self.paginate_comments(self.object)
        context['comments'] = comments
        context['page_obj'] = page
        context['is_paginated'] = is_paginated

        return context

    def paginate_comments(self, article):
        comments = article.comments.all().order_by('-created_at')
        if comments.count() > 0:
            paginator = Paginator(comments, self.paginate_comments_by, orphans=self.paginate_comments_orphans)
            page_number = self.request.GET.get('page', 1)
            page = paginator.get_page(page_number)
            is_paginated = paginator.num_pages > 1  # page.has_other_pages()
            return page.object_list, page, is_paginated
        else:
            return comments, None, False


class ArticleCreateView(LoginRequiredMixin, CreateView):
    template_name = 'article/article_create.html'
    form_class = ArticleForm
    model = Article

    # def form_valid(self, form):
    #     form.instance.author = self.request.user
    #     response = super().form_valid(form)
    #     tag, _ = Tag.objects.get_or_create(name=self.request.user.username)
    #     form.instance.tags.add(tag)
    #     return response
    #
    # def get_success_url(self):
    #     return reverse('webapp:article_view', kwargs={'pk': self.object.pk})

    def form_valid(self, form):
        article = form.save(commit=False)
        article.author = self.request.user
        article.save()
        form.save_m2m()
        tag, _ = Tag.objects.get_or_create(name=self.request.user.username)
        article.tags.add(tag)
        return redirect('webapp:article_view', pk=article.pk)


class ArticleUpdateView(PermissionRequiredMixin, UpdateView):
    template_name = 'article/article_update.html'
    form_class = ArticleForm
    model = Article
    permission_required = 'webapp.change_article'

    def has_permission(self):
        article = self.get_object()
        return super().has_permission() or article.author == self.request.user

    def get_initial(self):
        return {'publish_at': make_naive(self.object.publish_at)\
            .strftime(BROWSER_DATETIME_FORMAT)}

    # def form_valid(self, form):
    #     response = super().form_valid(form)
    #     tag, _ = Tag.objects.get_or_create(name=self.request.user.username)
    #     form.instance.tags.add(tag)
    #     return response
    #
    # def get_success_url(self):
    #     return reverse('webapp:article_view', kwargs={'pk': self.object.pk})

    def form_valid(self, form):
        article = form.save()
        tag, _ = Tag.objects.get_or_create(name=self.request.user.username)
        article.tags.add(tag)
        return redirect('webapp:article_view', pk=article.pk)


class ArticleDeleteView(UserPassesTestMixin, DeleteView):
    template_name = 'article/article_delete.html'
    model = Article
    success_url = reverse_lazy('webapp:index')

    def test_func(self):
        return self.request.user.has_perm('webapp.delete_article') or \
            self.get_object().author == self.request.user


class ArticleLikeView(LoginRequiredMixin, View):
    def post(self, request, *args, **kwargs):
        article = get_object_or_404(Article, pk=kwargs.get('pk'))
        like, created = ArticleLike.objects.get_or_create(article=article, user=request.user)
        if created:
            article.like_count += 1
            article.save()
            return HttpResponse(article.like_count)
        else:
            return HttpResponseForbidden()


class ArticleUnLikeView(LoginRequiredMixin, View):
    def delete(self, request, *args, **kwargs):
        article = get_object_or_404(Article, pk=kwargs.get('pk'))
        like = get_object_or_404(article.likes, user=request.user)
        like.delete()
        article.like_count -= 1
        article.save()
        return HttpResponse(article.like_count)


class GrantAccessView(LoginRequiredMixin, View):
    def post(self, request, *args, **kwargs):
        article = get_object_or_404(Article, pk=kwargs.get('pk'))
        user = get_object_or_404(get_user_model(), username=request.POST.get('username'))
        article.access_list.add(user)
        return HttpResponse('{"status": "ok"}')


class RemoveAccessView(LoginRequiredMixin, View):
    def post(self, request, *args, **kwargs):
        article = get_object_or_404(Article, pk=kwargs.get('pk'))
        user = get_object_or_404(get_user_model(), username=request.POST.get('username'))
        article.access_list.remove(user)
        return HttpResponse('{"status": "ok"}')

source/webapp/views/comment_views.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse
from django.views.generic import CreateView, UpdateView, DeleteView

from webapp.models import Comment, Article
from webapp.forms import ArticleCommentForm


class ArticleCommentCreateView(LoginRequiredMixin, CreateView):
    model = Comment
    template_name = 'comment/comment_create.html'
    form_class = ArticleCommentForm

    def form_valid(self, form):
        article = get_object_or_404(Article, pk=self.kwargs.get('pk'))
        comment = form.save(commit=False)
        comment.article = article
        comment.author = self.request.user
        comment.save()
        # form.save_m2m()  ## для сохранения связей многие-ко-многим
        return redirect('webapp:article_view', pk=article.pk)


class CommentUpdateView(PermissionRequiredMixin, UpdateView):
    model = Comment
    template_name = 'comment/comment_update.html'
    form_class = ArticleCommentForm
    permission_required = 'webapp.change_comment'

    def has_permission(self):
        comment = self.get_object()
        return super().has_permission() or comment.author == self.request.user

    def get_success_url(self):
        return reverse('webapp:article_view', kwargs={'pk': self.object.article.pk})


class CommentDeleteView(PermissionRequiredMixin, DeleteView):
    model = Comment
    permission_required = 'webapp.delete_comment'

    def get(self, request, *args, **kwargs):
        return self.delete(request, *args, **kwargs)

    def has_permission(self):
        comment = self.get_object()
        return super().has_permission() or comment.author == self.request.user

    def get_success_url(self):
        return reverse('webapp:article_view', kwargs={'pk': self.object.article.pk})

source/webapp/templates/base.html
{% load staticfiles %}
{% load i18n %}
{% load cache %}

<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}My Site{% endblock %}</title>

    <!-- XDSoft DateTimePicker -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.20/jquery.datetimepicker.min.css" integrity="sha256-DOS9W6NR+NFe1fUhEE0PGKY/fubbUCnOfTje2JMDw3Y=" crossorigin="anonymous" />

    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    {% block links %}{% endblock %}
</head>
<body>
    <nav class="navbar">
        <div class="container">
            <ul class="menu">
                <li><a href="{% url 'webapp:index' %}">Home</a></li>
                {% if request.user.is_authenticated %}
                    <li><a href="{% url 'webapp:article_create' %}">Add Article</a></li>
                    {% block menu %}{% endblock %}
                    <li><a href="{% url 'accounts:detail' request.user.pk %}">
                        Привет, {{ request.user.get_full_name|default:request.user.username }}
                    </a></li>
                {% endif %}

                {% cache 60 auth_menu request.user.is_authenticated %}
                    {% block auth_menu %}
                        {% if request.user.is_authenticated %}
                            <li><a href="{% url 'accounts:logout' %}?next={{ request.get_full_path }}">Logout</a></li>
                        {% else %}
                            <li><a href="{% url 'accounts:login' %}?next={{ request.get_full_path }}">Login</a></li>
                            <li><a href="{% url 'accounts:create' %}?next={{ request.get_full_path }}">Sign Up</a></li>
                        {% endif %}
                    {% endblock %}
                    {% if not request.user.is_authenticated %}
                        <li><a href="{% url 'accounts:password_reset_email' %}">Reset Password</a></li>
                    {% endif %}
                {% endcache %}
            </ul>

            {% block search %}
                <div class="search-form">
                    <form action="{% url 'webapp:index' %}" method="GET">
                        {{ search_form.search }}
                        <input type="submit" value="Найти">
                    </form>
                </div>

                <div class="lang-links">
                    {% get_current_language as LANGUAGE_CODE %}
                    {% get_available_languages as LANGUAGES %}
                    {% get_language_info_list for LANGUAGES as languages %}
                    {% get_language_info for LANGUAGE_CODE as current_language %}
                    {% for language in languages %}
                        <a class="lang-link {% if language.code == LANGUAGE_CODE %}active{% endif %}"
                           href="{% if language.code != default_language %}/{{ language.code }}{% endif %}{{ language_base_link }}">
                            {{ language.name_local }} ({{ language.code }})
                        </a>
                    {% endfor %}
                </div>
            {% endblock %}
        </div>
    </nav>
    <div class="container">
        {% block content %}{% endblock %}
    </div>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.20/jquery.datetimepicker.full.min.js" integrity="sha256-FEqEelWI3WouFOo2VWP/uJfs1y8KJ++FLh2Lbqc8SJk=" crossorigin="anonymous"></script>
    <script src="{% static "js/api_client.js" %}"></script>
    {% block scripts %}{% endblock %}

    <p class="version">{% if version %}{{ version }}{% endif %}</p>
</body>
</html>